package com.yogurt.model.entity.base;

import com.yogurt.model.entity.BaseModel;
import com.yogurt.model.vo.base.ProvinceVO;
import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.persistence.*;
import java.util.Optional;

@Data
@EqualsAndHashCode(callSuper = true)
@Table(name = "`dev_province`")
public class Province extends BaseModel {
    /**
     * ID
     */
    @Id
    @Column(name = "`ID`")
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator = "SELECT REPLACE(UUID(),'-','') UUID FROM DUAL")
    private String id;

    /**
     * 编码
     */
    @Column(name = "`CODE`")
    private String code;

    /**
     * 名称
     */
    @Column(name = "`NAME`")
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_province
     * @mbg.generated
     */
    @Override
    public ProvinceVO toVO() {
        ProvinceVO province = new ProvinceVO();

        Optional.ofNullable(this.getId()).ifPresent(province::setId);
        Optional.ofNullable(this.getCode()).ifPresent(province::setCode);
        Optional.ofNullable(this.getName()).ifPresent(province::setName);
        Optional.ofNullable(this.getStatus()).ifPresent(province::setStatus);
        Optional.ofNullable(this.getDelFlag()).ifPresent(province::setDelFlag);
        Optional.ofNullable(this.getCreateDate()).ifPresent(province::setCreateDate);
        Optional.ofNullable(this.getCreateUser()).ifPresent(province::setCreateUser);
        Optional.ofNullable(this.getModifyDate()).ifPresent(province::setModifyDate);
        Optional.ofNullable(this.getModifyUser()).ifPresent(province::setModifyUser);
        
        return province;
    }
}