package com.yogurt.model.entity.base;

import com.yogurt.model.entity.BaseModel;
import com.yogurt.model.vo.base.UserVO;
import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.persistence.*;
import java.util.Optional;

@Data
@EqualsAndHashCode(callSuper = true)
@Table(name = "`dev_user`")
public class User extends BaseModel {
    @Id
    @Column(name = "`ID`")
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator = "SELECT REPLACE(UUID(),'-','') UUID FROM DUAL")
    private String id;

    @Column(name = "`USER_NAME`")
    private String userName;

    @Column(name = "`PASSWORD`")
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     * @mbg.generated
     */
    @Override
    public UserVO toVO() {
        UserVO user = new UserVO();

        Optional.ofNullable(this.getId()).ifPresent(user::setId);
        Optional.ofNullable(this.getUserName()).ifPresent(user::setUserName);
        Optional.ofNullable(this.getPassword()).ifPresent(user::setPassword);
        Optional.ofNullable(this.getStatus()).ifPresent(user::setStatus);
        Optional.ofNullable(this.getDelFlag()).ifPresent(user::setDelFlag);
        Optional.ofNullable(this.getCreateDate()).ifPresent(user::setCreateDate);
        Optional.ofNullable(this.getCreateUser()).ifPresent(user::setCreateUser);
        Optional.ofNullable(this.getModifyDate()).ifPresent(user::setModifyDate);
        Optional.ofNullable(this.getModifyUser()).ifPresent(user::setModifyUser);
        
        return user;
    }
}