package com.yogurt.model.vo.base;

import com.yogurt.model.entity.base.Province;
import com.yogurt.model.vo.ViewObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.Optional;

@Data
@ApiModel
@EqualsAndHashCode(callSuper = true)
public class ProvinceVO extends ViewObject<Province> {
    @ApiModelProperty(value = "ID",hidden = true)
    String id;

    @ApiModelProperty("编码")
    String code;

    @ApiModelProperty("名称")
    String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_province
     * @mbg.generated
     */
    @Override
    public Province toEntity() {
        Province province = new Province();

        Optional.ofNullable(this.getId()).ifPresent(province::setId);
        Optional.ofNullable(this.getCode()).ifPresent(province::setCode);
        Optional.ofNullable(this.getName()).ifPresent(province::setName);
        Optional.ofNullable(this.getStatus()).ifPresent(province::setStatus);
        Optional.ofNullable(this.getDelFlag()).ifPresent(province::setDelFlag);
        Optional.ofNullable(this.getCreateDate()).ifPresent(province::setCreateDate);
        Optional.ofNullable(this.getCreateUser()).ifPresent(province::setCreateUser);
        Optional.ofNullable(this.getModifyDate()).ifPresent(province::setModifyDate);
        Optional.ofNullable(this.getModifyUser()).ifPresent(province::setModifyUser);

        return province;
    }
}