package com.yogurt.model.vo.base;

import com.yogurt.model.entity.base.User;
import com.yogurt.model.vo.ViewObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.Optional;

@Data
@ApiModel
@EqualsAndHashCode(callSuper = true)
public class UserVO extends ViewObject<User> {
    @ApiModelProperty("ID")
    String id;

    @ApiModelProperty("用户名")
    String userName;

    @ApiModelProperty("密码")
    String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     * @mbg.generated
     */
    @Override
    public User toEntity() {
        User user = new User();

        Optional.ofNullable(this.getId()).ifPresent(user::setId);
        Optional.ofNullable(this.getUserName()).ifPresent(user::setUserName);
        Optional.ofNullable(this.getPassword()).ifPresent(user::setPassword);
        Optional.ofNullable(this.getStatus()).ifPresent(user::setStatus);
        Optional.ofNullable(this.getDelFlag()).ifPresent(user::setDelFlag);
        Optional.ofNullable(this.getCreateDate()).ifPresent(user::setCreateDate);
        Optional.ofNullable(this.getCreateUser()).ifPresent(user::setCreateUser);
        Optional.ofNullable(this.getModifyDate()).ifPresent(user::setModifyDate);
        Optional.ofNullable(this.getModifyUser()).ifPresent(user::setModifyUser);

        return user;
    }
}