# global user config
system:
  version: 1.0.1-SNAPSHOT

server:
  port: 8080
  servlet:
    context-path: /otwb

# default logger config
logging:
  level:
    root: debug
    springfox.documentation: warn
    org.springframework: warn
    org.hibernate: warn
    org.thymeleaf: warn
    org.apache: warn
    org.quartz: warn
    io.swagger: warn
    org.zbus: warn
    sun.rmi: warn
  file: ./otwb.log

spring:
  # default druid config
  datasource:
    name: druid
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    validationQuery: SELECT 1 FROM DUAL
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    # 连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 超时回收 并打印信息 默认五分钟
    logAbandoned: true
    removeAbandoned: true
    removeAbandonedTimeout: 300
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    resetStatEnable: false
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
# default multipart upload config
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB
# default thymeleaf config
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

# default mybatis config
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.yogurt.model.entity

# default pagehelper config
# see https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md
pagehelper:
  # 分页合理化参数 <=0查询第一页 >=pages查询最后一页
  reasonable: true
  autoRuntimeDialect: true
  support-methods-arguments: true
  params: pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
  row-bounds-with-count: true
  pageSizeZero: true

# default tk mybatis mapper config
mapper:
  # <selectKey>中的order属性 执行SQL的返回主键时机, oracle为BEFORE MySQL为AFTER
  before: false
  identity: MYSQL
  # insertSelective 和 updateByPrimaryKeySelective 中，是否判断字符串类型 !=''。
  not-empty: true
  style: camelhumpAndUppercase
  use-simple-type: true
  # 校验通用 Example 构造参数 entityClass 是否和当前调用的 Mapper<EntityClass> 类型一致。
  check-example-entity-class: true
  # 必须设置查询条件才能删除和更新
  safe-delete: true
  safe-update: true
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.MySqlMapper #mysql特有