# global user config
system:
  version: 0.1

server:
  port: 8080
  servlet:
    context-path: /otwb

# default logger config
logging:
  config: classpath:logback.xml

spring:
  datasource:
    name: druid
    url: jdbc:mysql://localhost:3306/chjwms?characterEncoding=utf8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    validationQuery: SELECT 1 FROM DUAL
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    # 连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 超时回收 并打印信息 默认五分钟
    logAbandoned: true
    removeAbandoned: true
    removeAbandonedTimeout: 300
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    resetStatEnable: false
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB
      location: E:\\
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  jpa:
    open-in-view: true
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true