package com.yogurt.model.entity.global;

import com.yogurt.model.entity.BaseModel;
import com.yogurt.model.vo.global.VersionVO;
import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.persistence.*;
import java.util.Optional;

@Data
@EqualsAndHashCode(callSuper = true)
@Table(name = "`dev_version`")
public class Version extends BaseModel {
    /**
     * ID
     */
    @Id
    @Column(name = "`ID`")
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator = "SELECT REPLACE(UUID(),'-','') UUID FROM DUAL")
    private String id;

    /**
     * 版本
     */
    @Column(name = "`VERSION`")
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_version
     * @mbg.generated
     */
    @Override
    public VersionVO toVO() {
        VersionVO version = new VersionVO();

        Optional.ofNullable(this.getId()).ifPresent(version::setId);
        Optional.ofNullable(this.getVersion()).ifPresent(version::setVersion);
        Optional.ofNullable(this.getStatus()).ifPresent(version::setStatus);
        Optional.ofNullable(this.getDelFlag()).ifPresent(version::setDelFlag);
        Optional.ofNullable(this.getCreateDate()).ifPresent(version::setCreateDate);
        Optional.ofNullable(this.getCreateUser()).ifPresent(version::setCreateUser);
        Optional.ofNullable(this.getModifyDate()).ifPresent(version::setModifyDate);
        Optional.ofNullable(this.getModifyUser()).ifPresent(version::setModifyUser);
        
        return version;
    }
}